import { useState } from 'react';
import type { FootprintDto } from '@bliver/contracts';
import { Button, Surface } from '@bliver/ui';
import { addReaction as defaultAddReaction, removeReaction as defaultRemoveReaction, reportFootprint as defaultReport } from './api.js';
import { ConversationSection } from './ConversationSection.js';

export interface ActivityCardProps { readonly item: FootprintDto; readonly onAuthRequired?: (action: Record<string, string>) => void; readonly addReaction?: (id: string, emoji: string) => Promise<unknown>; readonly removeReaction?: (id: string) => Promise<void>; readonly report?: (id: string, reason: 'spam') => Promise<unknown>; }
export function ActivityCard({ item, onAuthRequired, addReaction = defaultAddReaction, removeReaction = defaultRemoveReaction, report = defaultReport }: ActivityCardProps) { const [reaction, setReaction] = useState<string | null>(null); const [expanded, setExpanded] = useState(false); const [notice, setNotice] = useState(''); const react = async (emoji: string): Promise<void> => { const prior = reaction; setReaction(prior === emoji ? null : emoji); try { if (prior === emoji) await removeReaction(item.id); else await addReaction(item.id, emoji); } catch (cause) { setReaction(prior); if (cause instanceof Error && cause.message === 'AUTH_REQUIRED') { onAuthRequired?.({ kind: 'reaction', footprintId: item.id, emoji }); setNotice('Sign in to react.'); } else setNotice('Reaction did not save.'); } }; const submitReport = async (): Promise<void> => { try { await report(item.id, 'spam'); setNotice('Report received.'); } catch (cause) { if (cause instanceof Error && cause.message === 'AUTH_REQUIRED') { onAuthRequired?.({ kind: 'report', footprintId: item.id, reason: 'spam' }); setNotice('Sign in to report this moment.'); } else setNotice('Report could not be sent.'); } };
  return <Surface className="activity-card"><header><div><strong>{item.author.name}</strong><time dateTime={item.publishedAt}>{new Date(item.publishedAt).toLocaleString()}</time></div><span>{item.visibility === 'public' ? 'Public' : item.visibility === 'friends' ? 'Friends' : 'Only you'}</span></header><p className="activity-card__message">{item.message ?? 'Shared a moment'}</p><p className="activity-card__place">{item.locationPrecision === 'precise' ? 'Exact place' : 'Nearby area'}</p><div className="activity-card__tools" aria-label="Moment actions"><Button variant={reaction === 'heart' ? 'primary' : 'ghost'} aria-label="React with heart" onClick={() => void react('heart')}>Heart</Button><Button variant="ghost" aria-expanded={expanded} onClick={() => setExpanded((value) => !value)}>Comment</Button><Button variant="ghost" onClick={() => void submitReport()}>Report</Button></div>{notice ? <p role="status">{notice}</p> : null}{expanded ? <ConversationSection footprintId={item.id} {...(onAuthRequired ? { onAuthRequired } : {})} /> : null}</Surface>;
}
