import { activityPageDto, commentsResponse, reactionDto, reportCreatedResponse, type ActivityQuery } from '@bliver/contracts';
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';

export async function fetchActivity(query: ActivityQuery) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (value !== undefined) params.set(key, String(value)); const response = await fetch(`/api/v1/activity?${params.toString()}`, { credentials: 'include' }); if (!response.ok) throw new Error('ACTIVITY_REQUEST_FAILED'); return activityPageDto.parse(await response.json()); }
export function useActivityQuery(query: ActivityQuery, enabled = true) { return useQuery({ queryKey: ['activity', query], queryFn: () => fetchActivity(query), enabled, retry: 1, staleTime: 15_000 }); }
export function useActivityInfiniteQuery(query: ActivityQuery, enabled = true) { return useInfiniteQuery({ queryKey: ['activity', query], initialPageParam: undefined as string | undefined, queryFn: ({ pageParam }) => fetchActivity({ ...query, ...(pageParam ? { cursor: pageParam } : {}) }), getNextPageParam: (last) => last.nextCursor, enabled, retry: 1, staleTime: 15_000 }); }
async function json(response: Response): Promise<unknown> { if (response.status === 401) throw new Error('AUTH_REQUIRED'); if (!response.ok) throw new Error('INTERACTION_REQUEST_FAILED'); return response.json(); }
export async function addReaction(footprintId: string, emoji: string) { const response = await fetch(`/api/v1/footprints/${encodeURIComponent(footprintId)}/reactions`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ emoji }) }); return reactionDto.parse(await json(response)); }
export async function removeReaction(footprintId: string): Promise<void> { const response = await fetch(`/api/v1/footprints/${encodeURIComponent(footprintId)}/reactions`, { method: 'DELETE', credentials: 'include' }); if (response.status === 401) throw new Error('AUTH_REQUIRED'); if (!response.ok) throw new Error('INTERACTION_REQUEST_FAILED'); }
export async function loadComments(footprintId: string) { const response = await fetch(`/api/v1/footprints/${encodeURIComponent(footprintId)}/comments`, { credentials: 'include' }); return commentsResponse.parse(await json(response)).items; }
export async function addComment(footprintId: string, content: string) { const response = await fetch(`/api/v1/footprints/${encodeURIComponent(footprintId)}/comments`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ content }) }); return json(response); }
export async function addReply(footprintId: string, parentCommentId: string, content: string) { const response = await fetch(`/api/v1/footprints/${encodeURIComponent(footprintId)}/comments/${encodeURIComponent(parentCommentId)}/replies`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ content }) }); return json(response); }
export async function reportFootprint(footprintId: string, reason: 'spam' | 'harassment' | 'hate' | 'privacy' | 'illegal' | 'other') { const response = await fetch('/api/v1/reports', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ footprintId, reason }) }); return reportCreatedResponse.parse(await json(response)); }
