import { useEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@bliver/ui';
import { Link, useLocation } from 'react-router-dom';
import type { CommentDto } from '@bliver/contracts';
import { addComment as defaultAddComment, addReply as defaultAddReply, loadComments as defaultLoadComments } from './api.js';
import { consumePendingAction, type PendingAction } from '../../platform/pending-action.js';

export interface ConversationSectionProps { readonly footprintId: string; readonly comments?: readonly CommentDto[]; readonly load?: (id: string) => Promise<readonly CommentDto[]>; readonly addComment?: (id: string, content: string) => Promise<unknown>; readonly addReply?: (id: string, parentId: string, content: string) => Promise<unknown>; readonly onAuthRequired?: (action: Record<string, string>) => void; }
export function ConversationSection({ footprintId, comments: initial = [], load = defaultLoadComments, addComment = defaultAddComment, addReply = defaultAddReply, onAuthRequired }: ConversationSectionProps) {
  const [content, setContent] = useState(''); const [replyTo, setReplyTo] = useState<string | null>(null); const [error, setError] = useState(''); const [authRequired, setAuthRequired] = useState(false); const location = useLocation(); const replayed = useRef<string | null>(null); const query = useQuery({ queryKey: ['footprint', footprintId, 'comments'], queryFn: () => load(footprintId), ...(initial.length ? { initialData: initial } : {}), retry: 1 }); const comments = query.data ?? initial;
  useEffect(() => { const pending = (location.state as { pendingAction?: PendingAction } | null)?.pendingAction; if (!location.pathname.startsWith('/footprints/')) return; if (!pending || pending.footprintId !== footprintId || (pending.kind !== 'comment' && pending.kind !== 'reply') || !pending.content) return; const pendingContent = pending.content; const fingerprint = JSON.stringify(pending); if (replayed.current === fingerprint) return; replayed.current = fingerprint; void (async () => { try { if (pending.kind === 'reply' && pending.parentCommentId) await addReply(footprintId, pending.parentCommentId, pendingContent); else if (pending.kind === 'comment') await addComment(footprintId, pendingContent); consumePendingAction(); await query.refetch(); } catch { return; } })(); }, [addComment, addReply, footprintId, location.pathname, location.state, query]);
  const submit = async (): Promise<void> => { const value = content.trim(); if (!value) return; try { if (replyTo) await addReply(footprintId, replyTo, value); else await addComment(footprintId, value); setContent(''); setReplyTo(null); setError(''); setAuthRequired(false); await query.refetch(); } catch (cause) { if (cause instanceof Error && cause.message === 'AUTH_REQUIRED') { onAuthRequired?.({ kind: replyTo ? 'reply' : 'comment', footprintId, content: value, ...(replyTo ? { parentCommentId: replyTo } : {}) }); setAuthRequired(true); setError('Sign in to join the conversation.'); } else { setAuthRequired(false); setError('Your comment was not posted. Try again.'); } } };
  return <section className="conversation" aria-label="Conversation"><div className="conversation__heading"><strong>Conversation</strong>{query.isLoading ? <span role="status">Loading comments</span> : <span>{comments.length}</span>}</div>{query.isError ? <p role="alert">Comments could not be loaded.</p> : null}{error ? <p role="alert">{error}{authRequired ? <> <Link to="/login">Sign in</Link></> : null}</p> : null}<ol>{comments.map((comment) => <li key={comment.id}><div><strong>{comment.author.name}</strong><p>{comment.content}</p><Button variant="ghost" onClick={() => setReplyTo(comment.id)}>Reply</Button></div>{comment.replies.length ? <ol>{comment.replies.map((reply) => <li key={reply.id}><strong>{reply.author.name}</strong><p>{reply.content}</p></li>)}</ol> : null}</li>)}</ol><label className="conversation__composer">{replyTo ? 'Write a reply' : 'Add a comment'}<textarea aria-label={replyTo ? 'Reply' : 'Comment'} value={content} maxLength={2000} onChange={(event) => setContent(event.target.value)} /></label><div className="conversation__actions">{replyTo ? <Button variant="ghost" onClick={() => setReplyTo(null)}>Cancel reply</Button> : null}<Button variant="secondary" onClick={() => void submit()} disabled={!content.trim()}>Post</Button></div></section>;
}
