import { createEventId, parseFootprintId, parseUserId, type FootprintId } from '@bliver/domain';
import type { ActorContext } from '../../identity/index.js';
import type { AddCommentInput } from '@bliver/contracts';
import { assertEmoji, createCommentId, InteractionError, type Comment, type InteractionEvent, type Reaction, validActor } from '../domain/model.js';
import type { InteractionAccess, InteractionRepository } from './ports.js';

function event(type: InteractionEvent['type'], footprintId: FootprintId, payload: Record<string, unknown>): InteractionEvent { return { id: createEventId(), type, aggregateId: footprintId, payload }; }

export class InteractionService {
  constructor(private readonly repository: InteractionRepository, private readonly access: InteractionAccess, private readonly now: () => Date = () => new Date()) {}
  async addReaction(actor: ActorContext | null, footprintId: string, emoji: string): Promise<Reaction> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); const value = assertEmoji(emoji); const current = await this.repository.findReaction(id, parseUserId(actor.userId)); const reaction: Reaction = { footprintId: id, actorId: parseUserId(actor.userId), emoji: value, createdAt: current?.createdAt ?? this.now() }; await this.repository.saveReaction(reaction); await this.repository.appendEvent(event('ReactionAdded', id, { actorId: actor.userId, emoji: value })); return reaction; }
  async removeReaction(actor: ActorContext | null, footprintId: string): Promise<void> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); await this.repository.removeReaction(id, parseUserId(actor.userId)); await this.repository.appendEvent(event('ReactionRemoved', id, { actorId: actor.userId })); }
  async addComment(actor: ActorContext | null, input: AddCommentInput): Promise<Comment> { validActor(actor); const id = parseFootprintId(input.footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); if (input.parentCommentId) { const parent = await this.repository.findComment(input.parentCommentId); if (!parent || parent.footprintId !== id || parent.parentCommentId) throw new InteractionError('COMMENT_DEPTH_INVALID'); return this.createComment(actor, id, input.content, parent.id); } return this.createComment(actor, id, input.content, null); }
  async addReply(actor: ActorContext | null, footprintId: string, parentCommentId: string, content: string): Promise<Comment> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); const parent = await this.repository.findComment(parentCommentId); if (!parent || parent.footprintId !== id) throw new InteractionError('COMMENT_PARENT_INVALID'); if (parent.parentCommentId) throw new InteractionError('COMMENT_DEPTH_INVALID'); return this.createComment(actor, id, content, parent.id); }
  async deleteComment(actor: ActorContext | null, commentId: string): Promise<void> { validActor(actor); const comment = await this.repository.findComment(commentId); if (!comment) throw new InteractionError('COMMENT_FORBIDDEN'); const allowed = comment.authorId === parseUserId(actor.userId) || actor.roles.includes('admin'); if (!allowed) throw new InteractionError('COMMENT_FORBIDDEN'); await this.repository.updateCommentDeleted(comment.id, this.now()); await this.repository.appendEvent(event('CommentDeleted', comment.footprintId, { commentId: comment.id, actorId: actor.userId })); }
  async listComments(actor: ActorContext | null, footprintId: string): Promise<Comment[]> { const id = parseFootprintId(footprintId); if (this.access.canRead && !(await this.access.canRead(actor, id))) throw new InteractionError('BLOCKED'); return (await this.repository.listComments(id)).filter((comment) => !comment.deletedAt).sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime() || a.id.localeCompare(b.id)); }
  async listReactions(actor: ActorContext | null, footprintId: string): Promise<Reaction[]> { const id = parseFootprintId(footprintId); if (this.access.canRead && !(await this.access.canRead(actor, id))) throw new InteractionError('BLOCKED'); return (await this.repository.listReactions(id)).sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime()); }
  private async createComment(actor: ActorContext, footprintId: FootprintId, content: string, parentCommentId: string | null): Promise<Comment> { const trimmed = content.trim(); if (!trimmed || trimmed.length > 2_000) throw new InteractionError('COMMENT_PARENT_INVALID'); const comment: Comment = { id: createCommentId(), footprintId, authorId: parseUserId(actor.userId), authorName: actor.userId, content: trimmed, parentCommentId, createdAt: this.now(), deletedAt: null }; await this.repository.saveComment(comment); await this.repository.appendEvent(event('CommentAdded', footprintId, { commentId: comment.id, actorId: actor.userId, parentCommentId })); return comment; }
}

export function createMemoryInteractionRepository(): InteractionRepository {
  const reactions = new Map<string, Reaction>(); const comments = new Map<string, Comment>(); const events: InteractionEvent[] = [];
  return { async findReaction(footprintId, actorId) { return reactions.get(`${footprintId}:${actorId}`) ?? null; }, async saveReaction(reaction) { reactions.set(`${reaction.footprintId}:${reaction.actorId}`, reaction); }, async removeReaction(footprintId, actorId) { reactions.delete(`${footprintId}:${actorId}`); }, async listReactions(footprintId) { return [...reactions.values()].filter((item) => item.footprintId === footprintId); }, async findComment(id) { return comments.get(id) ?? null; }, async saveComment(comment) { comments.set(comment.id, comment); }, async updateCommentDeleted(id, at) { const item = comments.get(id); if (item) comments.set(id, { ...item, deletedAt: at }); }, async listComments(footprintId) { return [...comments.values()].filter((item) => item.footprintId === footprintId); }, async appendEvent(item) { events.push(item); } };
}
