import { createEventId, parseFootprintId, parseUserId, type FootprintId } from '@bliver/domain';
import type { ActorContext } from '../../identity/index.js';
import type { AddCommentInput } from '@bliver/contracts';
import { assertEmoji, createCommentId, InteractionError, type Comment, type InteractionEvent, type Reaction, validActor } from '../domain/model.js';
import type { InteractionAccess, InteractionRepository } from './ports.js';
import type { IdempotentCommentCommit } from './ports.js';

function event(type: InteractionEvent['type'], footprintId: FootprintId, payload: Record<string, unknown>): InteractionEvent { return { id: createEventId(), type, aggregateId: footprintId, payload }; }

export class InteractionService {
  constructor(private readonly repository: InteractionRepository, private readonly access: InteractionAccess, private readonly now: () => Date = () => new Date()) {}
  async addReaction(actor: ActorContext | null, footprintId: string, emoji: string): Promise<Reaction> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); const value = assertEmoji(emoji); const current = await this.repository.findReaction(id, parseUserId(actor.userId)); const reaction: Reaction = { footprintId: id, actorId: parseUserId(actor.userId), emoji: value, createdAt: current?.createdAt ?? this.now() }; const added = event('ReactionAdded', id, { actorId: actor.userId, emoji: value }); if (this.repository.transactions) await this.repository.transactions.addReaction({ reaction, event: added }); else { await this.repository.saveReaction(reaction); await this.repository.appendEvent(added); } return reaction; }
  async removeReaction(actor: ActorContext | null, footprintId: string): Promise<void> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); const actorId = parseUserId(actor.userId); const removed = event('ReactionRemoved', id, { actorId: actor.userId }); if (this.repository.transactions) await this.repository.transactions.removeReaction({ footprintId: id, actorId, event: removed }); else { await this.repository.removeReaction(id, actorId); await this.repository.appendEvent(removed); } }
  async addComment(actor: ActorContext | null, input: AddCommentInput, idempotency?: Pick<IdempotentCommentCommit, 'key' | 'fingerprint'>): Promise<Comment> { validActor(actor); const id = parseFootprintId(input.footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); if (input.parentCommentId) { const parent = await this.repository.findComment(input.parentCommentId); if (!parent || parent.deletedAt || parent.footprintId !== id || parent.parentCommentId) throw new InteractionError('COMMENT_DEPTH_INVALID'); return this.createComment(actor, id, input.content, parent.id, idempotency ? { ...idempotency, scope: 'interaction.reply' } : undefined); } return this.createComment(actor, id, input.content, null, idempotency ? { ...idempotency, scope: 'interaction.comment' } : undefined); }
  async addReply(actor: ActorContext | null, footprintId: string, parentCommentId: string, content: string, idempotency?: Pick<IdempotentCommentCommit, 'key' | 'fingerprint'>): Promise<Comment> { validActor(actor); const id = parseFootprintId(footprintId); if (!(await this.access.canInteract(actor, id))) throw new InteractionError('BLOCKED'); const parent = await this.repository.findComment(parentCommentId); if (!parent || parent.deletedAt || parent.footprintId !== id) throw new InteractionError('COMMENT_PARENT_INVALID'); if (parent.parentCommentId) throw new InteractionError('COMMENT_DEPTH_INVALID'); return this.createComment(actor, id, content, parent.id, idempotency ? { ...idempotency, scope: 'interaction.reply' } : undefined); }
  async deleteComment(actor: ActorContext | null, commentId: string): Promise<void> { validActor(actor); const comment = await this.repository.findComment(commentId); if (!comment) throw new InteractionError('COMMENT_FORBIDDEN'); const actorId = parseUserId(actor.userId); const ownerId = await this.access.footprintOwner(comment.footprintId); const allowed = comment.authorId === actorId || ownerId === actorId || actor.roles.includes('admin'); if (!allowed) throw new InteractionError('COMMENT_FORBIDDEN'); const at = this.now(); const deleted = event('CommentDeleted', comment.footprintId, { commentId: comment.id, actorId: actor.userId }); if (this.repository.transactions) await this.repository.transactions.deleteComment({ commentId: comment.id, at, event: deleted }); else { await this.repository.updateCommentDeleted(comment.id, at); await this.repository.appendEvent(deleted); } }
  async listComments(actor: ActorContext | null, footprintId: string): Promise<Comment[]> { const id = parseFootprintId(footprintId); if (this.access.canRead && !(await this.access.canRead(actor, id))) throw new InteractionError('BLOCKED'); const comments = (await this.repository.listComments(id)).filter((comment) => !comment.deletedAt); const visible = actor ? (await Promise.all(comments.map(async (comment) => ({ comment, blocked: await this.access.isBlocked(parseUserId(actor.userId), comment.authorId) })))).filter((item) => !item.blocked).map((item) => item.comment) : comments; return visible.sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime() || a.id.localeCompare(b.id)); }
  async listReactions(actor: ActorContext | null, footprintId: string): Promise<Reaction[]> { const id = parseFootprintId(footprintId); if (this.access.canRead && !(await this.access.canRead(actor, id))) throw new InteractionError('BLOCKED'); const reactions = await this.repository.listReactions(id); const visible = actor ? (await Promise.all(reactions.map(async (reaction) => ({ reaction, blocked: await this.access.isBlocked(parseUserId(actor.userId), reaction.actorId) })))).filter((item) => !item.blocked).map((item) => item.reaction) : reactions; return visible.sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime()); }
  private async createComment(actor: ActorContext, footprintId: FootprintId, content: string, parentCommentId: string | null, idempotency?: Pick<IdempotentCommentCommit, 'key' | 'fingerprint' | 'scope'>): Promise<Comment> { const trimmed = content.trim(); if (!trimmed || trimmed.length > 2_000) throw new InteractionError('COMMENT_PARENT_INVALID'); const comment: Comment = { id: createCommentId(), footprintId, authorId: parseUserId(actor.userId), authorName: actor.displayName ?? actor.userId, content: trimmed, parentCommentId, createdAt: this.now(), deletedAt: null }; const added = event('CommentAdded', footprintId, { commentId: comment.id, actorId: actor.userId, parentCommentId }); if (idempotency && this.repository.commitComment) return this.repository.commitComment({ actorId: comment.authorId, ...idempotency, comment, event: added }); if (this.repository.transactions) await this.repository.transactions.addComment({ comment, event: added }); else { await this.repository.saveComment(comment); await this.repository.appendEvent(added); } return comment; }
}

export function createMemoryInteractionRepository(): InteractionRepository {
  const reactions = new Map<string, Reaction>(); const comments = new Map<string, Comment>(); const events: InteractionEvent[] = []; const idempotency = new Map<string, { fingerprint: string; comment: Comment }>();
  const transactions = { async addReaction(input: { reaction: Reaction; event: InteractionEvent }) { reactions.set(`${input.reaction.footprintId}:${input.reaction.actorId}`, input.reaction); events.push(input.event); }, async removeReaction(input: { footprintId: FootprintId; actorId: ReturnType<typeof parseUserId>; event: InteractionEvent }) { reactions.delete(`${input.footprintId}:${input.actorId}`); events.push(input.event); }, async addComment(input: { comment: Comment; event: InteractionEvent }) { comments.set(input.comment.id, input.comment); events.push(input.event); }, async deleteComment(input: { commentId: string; at: Date; event: InteractionEvent }) { const item = comments.get(input.commentId); if (item) comments.set(input.commentId, { ...item, deletedAt: input.at }); events.push(input.event); } };
  return { transactions, async findReaction(footprintId, actorId) { return reactions.get(`${footprintId}:${actorId}`) ?? null; }, async saveReaction(reaction) { reactions.set(`${reaction.footprintId}:${reaction.actorId}`, reaction); }, async removeReaction(footprintId, actorId) { reactions.delete(`${footprintId}:${actorId}`); }, async listReactions(footprintId) { return [...reactions.values()].filter((item) => item.footprintId === footprintId); }, async findComment(id) { return comments.get(id) ?? null; }, async saveComment(comment) { comments.set(comment.id, comment); }, async updateCommentDeleted(id, at) { const item = comments.get(id); if (item) comments.set(id, { ...item, deletedAt: at }); }, async listComments(footprintId) { return [...comments.values()].filter((item) => item.footprintId === footprintId); }, async appendEvent(item) { events.push(item); }, async commitComment(input) { const key = `${input.actorId}:${input.scope}:${input.key}`; const prior = idempotency.get(key); if (prior) { if (prior.fingerprint !== input.fingerprint) throw new InteractionError('IDEMPOTENCY_CONFLICT'); return prior.comment; } idempotency.set(key, { fingerprint: input.fingerprint, comment: input.comment }); comments.set(input.comment.id, input.comment); events.push(input.event); return input.comment; } };
}
