import { describe, expect, it, vi } from 'vitest';
import { createFootprintId, createUserId } from '@bliver/domain';
import type { ActorContext } from '../../../identity/index.js';
import { CreateReport, createMemoryReportRepository, type Report } from '../reports.js';
const actor: ActorContext = { userId: createUserId(), sessionId: 'session', roles: ['user'], transport: 'bearer' }; const footprintId = createFootprintId();
describe('CreateReport', () => {
  it('rejects anonymous intake, invalid reasons, and duplicate open reports', async () => { const create = new CreateReport(createMemoryReportRepository(), { async canReport() { return true; } }); await expect(create.execute(null, { footprintId, reason: 'spam' })).rejects.toThrow('AUTH_REQUIRED'); await expect(create.execute(actor, { footprintId, reason: 'spam' })).resolves.toMatchObject({ status: 'open' }); await expect(create.execute(actor, { footprintId, reason: 'spam' })).rejects.toThrow('DUPLICATE_OPEN_REPORT'); });
  it('rejects blocked reporters before creating an intake record', async () => { const create = new CreateReport(createMemoryReportRepository(), { async canReport() { return false; } }); await expect(create.execute(actor, { footprintId, reason: 'harassment' })).rejects.toThrow('BLOCKED'); });
  it('passes report idempotency into the atomic transaction port', async () => { const createReport = vi.fn(async ({ report }: { report: Report }) => report); const repository = { ...createMemoryReportRepository(), transactions: { createReport } }; const create = new CreateReport(repository, { async canReport() { return true; } }); await create.execute(actor, { footprintId, reason: 'spam' }, { key: 'report-key', fingerprint: 'fingerprint' }); expect(createReport).toHaveBeenCalledWith(expect.objectContaining({ idempotency: expect.objectContaining({ key: 'report-key', fingerprint: 'fingerprint' }) })); });
  it('replays the same report key but rejects a distinct key for the existing open report', async () => { const create = new CreateReport(createMemoryReportRepository(), { async canReport() { return true; } }); const first = await create.execute(actor, { footprintId, reason: 'spam' }, { key: 'same-key', fingerprint: 'same' }); await expect(create.execute(actor, { footprintId, reason: 'spam' }, { key: 'same-key', fingerprint: 'same' })).resolves.toMatchObject({ id: first.id }); await expect(create.execute(actor, { footprintId, reason: 'spam' }, { key: 'different-key', fingerprint: 'same' })).rejects.toThrow('DUPLICATE_OPEN_REPORT'); });
  it('rolls back fake report reservation, mutation, and Outbox state after a crash', async () => { const base = createMemoryReportRepository(); let reservation = false; let mutations = 0; let events = 0; let fail = true; const repository = { ...base, transactions: { async createReport(input: Parameters<NonNullable<typeof base.transactions>['createReport']>[0]) { const snapshot = { reservation, mutations, events }; try { reservation = true; mutations += 1; events += 1; if (fail) { fail = false; throw new Error('simulated report crash'); } return input.report; } catch (error) { ({ reservation, mutations, events } = snapshot); throw error; } } } }; const create = new CreateReport(repository, { async canReport() { return true; } }); const idempotency = { key: 'report-crash', fingerprint: 'fingerprint' }; await expect(create.execute(actor, { footprintId, reason: 'spam' }, idempotency)).rejects.toThrow('simulated report crash'); expect({ reservation, mutations, events }).toEqual({ reservation: false, mutations: 0, events: 0 }); await expect(create.execute(actor, { footprintId, reason: 'spam' }, idempotency)).resolves.toMatchObject({ status: 'open' }); expect({ reservation, mutations, events }).toEqual({ reservation: true, mutations: 1, events: 1 }); });
});
