import { createEventId, parseFootprintId, parseUserId, type FootprintId, type UserId } from '@bliver/domain';
import type { DatabaseClient, DatabaseQueryPort } from '../../../platform/db/client.js';
import { FootprintConflictError, type FootprintOutboxEvent, type FootprintRecord, type FootprintRepositories, type FootprintTransactionPort, type MapFootprintRepository } from '../application/index.js';
import type { FootprintPolicyInput, FootprintPolicyRecordPort } from '../domain/visibility-policy.js';
import type { FootprintAuthorInput } from '../domain/visibility-policy.js';

type Row = Record<string, unknown>;
const date = (value: unknown): Date => new Date(String(value));
const point = (lat: unknown, lng: unknown) => ({ lat: Number(lat), lng: Number(lng) });
const author = (row: Row): FootprintAuthorInput => ({ name: String(row.author_name), ...(row.avatar_url ? { avatarUrl: String(row.avatar_url) } : {}) });
function policyRecord(row: Row): FootprintPolicyInput { return { id: parseFootprintId(String(row.id)), authorId: parseUserId(String(row.author_id)), author: author(row), displayPoint: point(row.display_lat, row.display_lng), visibility: row.visibility as FootprintPolicyInput['visibility'], locationPrecision: row.location_precision as FootprintPolicyInput['locationPrecision'], publishedAt: date(row.published_at), discoveryExpiresAt: row.discovery_expires_at ? date(row.discovery_expires_at) : null }; }
function fullRecord(row: Row): FootprintRecord { const metadata = row.metadata && typeof row.metadata === 'object' ? row.metadata as Record<string, unknown> : {}; return { ...policyRecord(row), privatePoint: point(row.private_lat, row.private_lng), message: String(row.message), ...(row.mood ? { mood: String(row.mood) } : {}), mediaAssetIds: Array.isArray(row.media_asset_ids) ? row.media_asset_ids.map(String) : [], metadata: { placeId: row.place_id ? String(row.place_id) : metadata.providerPlaceId ? String(metadata.providerPlaceId) : null, regionId: row.region_id ? String(row.region_id) : metadata.providerRegionId ? String(metadata.providerRegionId) : null, weather: metadata.weather ?? null } }; }

export interface PostgresFootprintRepositories extends FootprintRepositories, MapFootprintRepository, FootprintPolicyRecordPort {}

export function createPostgresFootprintRepositories(db: DatabaseClient): PostgresFootprintRepositories {
  const records = {
    async findById(id: FootprintId) { const result = await db.query<Row>(selectOwnerSql('WHERE f.id = $1'), [id]); return result.rows[0] ? fullRecord(result.rows[0]) : null; },
    async create(record: FootprintRecord) { await db.query(insertSql, insertValues(record)); },
    async updateVisibility(id: FootprintId, visibility: FootprintRecord['visibility']) { await db.query('UPDATE footprints SET visibility = $2, updated_at = now() WHERE id = $1', [id, visibility]); const result = await db.query<Row>(selectOwnerSql('WHERE f.id = $1'), [id]); return result.rows[0] ? fullRecord(result.rows[0]) : null; },
    async delete(id: FootprintId) { await db.query('DELETE FROM footprints WHERE id = $1', [id]); },
  };
  const outbox = { async append(event: FootprintOutboxEvent) { await db.query('INSERT INTO platform.outbox_events (id, type, aggregate_id, payload) VALUES ($1,$2,$3,$4)', [event.id, event.type, event.aggregateId, JSON.stringify(event.payload)]); }, async list() { const result = await db.query<Row>('SELECT id, type, aggregate_id, payload FROM platform.outbox_events ORDER BY created_at, id'); return result.rows.map((row) => ({ id: String(row.id), type: String(row.type) as FootprintOutboxEvent['type'], aggregateId: parseFootprintId(String(row.aggregate_id)), payload: row.payload as Record<string, unknown> })); } };
  const idempotency = { async find(actorId: UserId, key: string) { const result = await db.query<Row>('SELECT request_hash, response FROM platform.idempotency_keys WHERE actor_id = $1 AND scope = $2 AND key = $3', [actorId, 'footprint.publish', key]); const row = result.rows[0]; return row ? { fingerprint: String(row.request_hash), result: row.response as { footprint: FootprintRecord; outbox: FootprintOutboxEvent } } : null; }, async save(actorId: UserId, key: string, fingerprint: string, result: { footprint: FootprintRecord; outbox: FootprintOutboxEvent }) { await db.query('INSERT INTO platform.idempotency_keys (actor_id, scope, key, request_hash, response) VALUES ($1,$2,$3,$4,$5)', [actorId, 'footprint.publish', key, fingerprint, JSON.stringify(result)]); } };
  const transactions: FootprintTransactionPort = {
    async commitPublish(input) { return db.transaction(async (client) => commitPublish(client, input)); },
    async updateVisibility(input) { return db.transaction(async (client) => { const result = await client.query<Row>('UPDATE footprints SET visibility = $2, updated_at = now() WHERE id = $1 AND author_id = $3 RETURNING id', [input.footprintId, input.visibility, input.actorId]); if (!result.rowCount) throw new FootprintConflictError(); await client.query('INSERT INTO platform.outbox_events (id,type,aggregate_id,payload) VALUES ($1,$2,$3,$4)', [createEventId(), 'FootprintVisibilityUpdated', input.footprintId, JSON.stringify({ footprintId: input.footprintId, visibility: input.visibility })]); const record = await client.query<Row>(selectOwnerSql('WHERE f.id = $1'), [input.footprintId]); return fullRecord(record.rows[0] as Row); }); },
    async delete(input) { await db.transaction(async (client) => { const result = await client.query<Row>('DELETE FROM footprints WHERE id = $1 AND author_id = $2 RETURNING id', [input.footprintId, input.actorId]); if (!result.rowCount) throw new FootprintConflictError(); await client.query('INSERT INTO platform.outbox_events (id,type,aggregate_id,payload) VALUES ($1,$2,$3,$4)', [createEventId(), 'FootprintDeleted', input.footprintId, JSON.stringify({ footprintId: input.footprintId })]); }); },
  };
  const repository: PostgresFootprintRepositories = { footprints: records, outbox, idempotency, transactions, mediaOwnership: { async assertOwned() { return undefined; } }, publicDetails: { async findById(id) { const result = await db.query<Row>(selectPublicSql('WHERE f.id = $1'), [id]); const row = result.rows[0]; return row ? { ...policyRecord(row), message: String(row.message) } : null; } }, async findById(id) { const result = await db.query<Row>(selectPublicSql('WHERE f.id = $1'), [id]); return result.rows[0] ? policyRecord(result.rows[0]) : null; }, async listInViewport({ bounds, visibility, limit, cursor }) { const values: unknown[] = [bounds.west, bounds.south, bounds.east, bounds.north]; const predicates = ['f.display_point && ST_MakeEnvelope($1,$2,$3,$4,4326)::geography']; if (visibility) { values.push(visibility); predicates.push(`f.visibility = $${values.length}`); } if (cursor) { values.push(new Date(cursor.publishedAt), cursor.id); predicates.push(`(f.published_at < $${values.length - 1} OR (f.published_at = $${values.length - 1} AND f.id < $${values.length}))`); } if (limit) { values.push(Math.max(1, Math.min(100, Math.floor(limit)))); } const sql = `${selectPublicSql(`WHERE ${predicates.join(' AND ')}`)}${limit ? ` LIMIT $${values.length}` : ''}`; const result = await db.query<Row>(sql, values); return result.rows.map(policyRecord); } };
  return repository;
}

const insertSql = `INSERT INTO footprints (id, author_id, private_point, display_point, visibility, location_precision, message, mood, published_at, discovery_expires_at, place_id, region_id, metadata) VALUES ($1,$2,ST_SetSRID(ST_MakePoint($3,$4),4326)::geography,ST_SetSRID(ST_MakePoint($5,$6),4326)::geography,$7,$8,$9,$10,$11,$12,$13,$14,$15)`;
function uuidOrNull(value: string | null): string | null { return value && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value) ? value : null; }
function insertValues(record: FootprintRecord): readonly unknown[] { return [record.id, record.authorId, record.privatePoint.lng, record.privatePoint.lat, record.displayPoint.lng, record.displayPoint.lat, record.visibility, record.locationPrecision, record.message, record.mood ?? null, record.publishedAt, record.discoveryExpiresAt, uuidOrNull(record.metadata.placeId), uuidOrNull(record.metadata.regionId), JSON.stringify({ providerPlaceId: record.metadata.placeId, providerRegionId: record.metadata.regionId, weather: record.metadata.weather })]; }
function selectPublicSql(where: string): string { return `SELECT f.id, f.author_id, u.display_name AS author_name, ST_Y(f.display_point::geometry) AS display_lat, ST_X(f.display_point::geometry) AS display_lng, f.visibility, f.location_precision, f.message, f.published_at, f.discovery_expires_at FROM footprints f JOIN identity_users u ON u.id = f.author_id ${where} ORDER BY f.published_at DESC, f.id DESC`; }
function selectOwnerSql(where: string): string { return `SELECT f.id, f.author_id, u.display_name AS author_name, ST_Y(f.private_point::geometry) AS private_lat, ST_X(f.private_point::geometry) AS private_lng, ST_Y(f.display_point::geometry) AS display_lat, ST_X(f.display_point::geometry) AS display_lng, f.visibility, f.location_precision, f.message, f.mood, f.place_id, f.region_id, f.metadata, f.published_at, f.discovery_expires_at, COALESCE(array_agg(fm.asset_id::text) FILTER (WHERE fm.asset_id IS NOT NULL), ARRAY[]::text[]) AS media_asset_ids FROM footprints f JOIN identity_users u ON u.id = f.author_id LEFT JOIN footprint_media fm ON fm.footprint_id = f.id ${where} GROUP BY f.id, u.display_name ORDER BY f.published_at DESC, f.id DESC`; }
async function commitPublish(client: DatabaseQueryPort, input: Parameters<FootprintTransactionPort['commitPublish']>[0]): Promise<{ footprint: FootprintRecord; outbox: FootprintOutboxEvent }> {
  const response = { footprint: input.footprint, outbox: input.outbox };
  const reserved = await client.query<Row>('INSERT INTO platform.idempotency_keys (actor_id, scope, key, request_hash, response) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (actor_id, scope, key) DO NOTHING RETURNING request_hash, response', [input.actorId, 'footprint.publish', input.idempotencyKey, input.fingerprint, JSON.stringify(response)]);
  if (!reserved.rowCount) {
    const prior = await client.query<Row>('SELECT request_hash, response FROM platform.idempotency_keys WHERE actor_id = $1 AND scope = $2 AND key = $3', [input.actorId, 'footprint.publish', input.idempotencyKey]);
    const row = prior.rows[0];
    if (!row || String(row.request_hash) !== input.fingerprint) throw new FootprintConflictError();
    return parsePublishResult(row.response);
  }
  const result = await client.query<Row>(`SELECT count(*)::text AS count FROM media_assets WHERE owner_id = $1 AND id = ANY($2::uuid[])`, [input.actorId, input.footprint.mediaAssetIds]);
  if (input.footprint.mediaAssetIds.length && Number(result.rows[0]?.count ?? 0) !== input.footprint.mediaAssetIds.length) throw new FootprintConflictError();
  await client.query(insertSql, insertValues(input.footprint));
  for (const assetId of input.footprint.mediaAssetIds) await client.query('INSERT INTO footprint_media (id, footprint_id, asset_id, position) VALUES ($1,$2,$3,$4)', [createEventId(), input.footprint.id, assetId, input.footprint.mediaAssetIds.indexOf(assetId)]);
  await client.query('INSERT INTO platform.outbox_events (id,type,aggregate_id,payload) VALUES ($1,$2,$3,$4)', [input.outbox.id, input.outbox.type, input.outbox.aggregateId, JSON.stringify(input.outbox.payload)]);
  return response;
}

function parsePublishResult(value: unknown): { footprint: FootprintRecord; outbox: FootprintOutboxEvent } {
  const result = value as { footprint: FootprintRecord; outbox: FootprintOutboxEvent };
  return { ...result, footprint: { ...result.footprint, publishedAt: new Date(result.footprint.publishedAt), discoveryExpiresAt: result.footprint.discoveryExpiresAt ? new Date(result.footprint.discoveryExpiresAt) : null } };
}
