// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { CommentDto, FootprintDto } from '@bliver/contracts';
import { ActivityRoute } from '../ActivityRoute.js';
import { ActivityCard } from '../ActivityCard.js';
import { ConversationSection } from '../ConversationSection.js';

const footprintId = '019f0000-0000-7000-8000-000000000001'; const authorId = '019f0000-0000-7000-8000-000000000002';
const item: FootprintDto = { id: footprintId, author: { id: authorId, name: 'Lin' }, displayPoint: { lat: 31, lng: 121 }, visibility: 'public', locationPrecision: 'approximate', message: 'By the river', publishedAt: '2026-07-15T08:00:00.000Z', discoveryExpiresAt: '2026-07-16T08:00:00.000Z' };
function withQuery(node: React.ReactNode) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}>{node}</QueryClientProvider>); }
afterEach(cleanup);
describe('Activity discovery and interaction web surface', () => {
  it('renders loading, empty, error/retry, scope label, and cursor controls', () => { const retry = vi.fn(); const view = render(<ActivityRoute state="loading" />); expect(screen.getByRole('status')).toHaveTextContent('Loading activity'); view.rerender(<ActivityRoute state="empty" page={{ items: [], resolvedScope: 'country' }} />); expect(screen.getByRole('heading', { name: 'No moments in this view' })).toBeVisible(); view.rerender(<ActivityRoute state="error" onRetry={retry} />); fireEvent.click(screen.getByRole('button', { name: 'Try again' })); expect(retry).toHaveBeenCalledOnce(); view.rerender(<ActivityRoute page={{ items: [item], resolvedScope: 'region', nextCursor: 'next' }} />); expect(screen.getByText('Around your region')).toBeVisible(); expect(screen.getByRole('button', { name: 'Load more' })).toBeVisible(); });
  it('optimistically reacts and restores state while preserving a guest action', async () => { const pending = vi.fn(); withQuery(<ActivityCard item={item} addReaction={vi.fn(async () => { throw new Error('AUTH_REQUIRED'); })} onAuthRequired={pending} />); fireEvent.click(screen.getByRole('button', { name: 'React with heart' })); expect(screen.getByRole('button', { name: 'React with heart' })).toHaveClass('bliver-button--primary'); await screen.findByText('Sign in to react.'); expect(screen.getByRole('button', { name: 'React with heart' })).toHaveClass('bliver-button--ghost'); expect(pending).toHaveBeenCalledWith({ kind: 'reaction', footprintId, emoji: 'heart' }); });
  it('posts a top-level comment and reply through the same two-level conversation', async () => { const replyId = '019f0000-0000-7000-8000-000000000003'; const comments: CommentDto[] = [{ id: replyId, footprintId, author: { id: authorId, name: 'Lin' }, content: 'First', parentCommentId: null, createdAt: '2026-07-15T08:00:00.000Z', replies: [] }]; const addComment = vi.fn(async () => undefined); const addReply = vi.fn(async () => undefined); withQuery(<ConversationSection footprintId={footprintId} comments={comments} load={vi.fn(async () => comments)} addComment={addComment} addReply={addReply} />); fireEvent.change(screen.getByLabelText('Comment'), { target: { value: 'Hello' } }); fireEvent.click(screen.getByRole('button', { name: 'Post' })); await waitFor(() => expect(addComment).toHaveBeenCalledWith(footprintId, 'Hello')); fireEvent.click(screen.getByRole('button', { name: 'Reply' })); fireEvent.change(screen.getByLabelText('Reply'), { target: { value: 'Back' } }); fireEvent.click(screen.getByRole('button', { name: 'Post' })); await waitFor(() => expect(addReply).toHaveBeenCalledWith(footprintId, replyId, 'Back')); });
  it('confirms report intake without exposing moderation resolution', async () => { withQuery(<ActivityCard item={item} report={vi.fn(async () => ({ id: 'report', status: 'open' }))} />); fireEvent.click(screen.getByRole('button', { name: 'Report' })); expect(await screen.findByText('Report received.')).toBeVisible(); });
});
