import { randomUUID } from 'node:crypto';
import { Router, type Request } from 'express';
import type { IdentityRepositories } from '../../identity/application/ports.js';
import { requireActor, validMutationCsrf, type ActorContext } from '../../identity/transport/routes.js';
import type { NotificationService } from '../domain/service.js';

export interface NotificationRouterOptions { readonly service: NotificationService; readonly vapidPublicKey?: string; }
const actor = (request: Request) => (request as Request & { actor?: ActorContext }).actor;
export function notificationsRouter(options: NotificationRouterOptions, identity: IdentityRepositories): Router { const router=Router(); const auth=requireActor(identity); router.get('/notifications',auth,async(req,res)=>{ const current=actor(req); if(!current)return; res.json(await options.service.list(current.userId,typeof req.query.cursor==='string'?req.query.cursor:undefined)); }); router.post('/notifications/:id/read',auth,async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}await options.service.markRead(current.userId,String(req.params.id));res.status(204).end();}); router.post('/notifications/read-all',auth,async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}await options.service.markAllRead(current.userId);res.status(204).end();}); router.get('/notifications/preferences',auth,async(req,res)=>{const current=actor(req);if(!current)return;res.json(await options.service.getPreferences(current.userId));}); router.put('/notifications/preferences',auth,async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}res.json(await options.service.setPreferences(current.userId,req.body as Record<string,boolean>));}); router.get('/push/public-key',(_req,res)=>{if(!options.vapidPublicKey){res.status(404).json({code:'PUSH_UNAVAILABLE'});return;}res.json({publicKey:options.vapidPublicKey});}); router.post('/push/subscribe',auth,async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}const input=req.body as { endpoint?: string; keys?: { p256dh?: string; auth?: string } };if(!input.endpoint||!input.keys?.p256dh||!input.keys.auth){res.status(400).json({code:'INVALID_REQUEST'});return;}await options.service.subscribe({id:randomUUID(),userId:current.userId,endpoint:input.endpoint,p256dh:input.keys.p256dh,auth:input.keys.auth});res.status(201).json({ok:true});}); router.post('/push/unsubscribe',auth,async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}if(typeof req.body?.endpoint!=='string'){res.status(400).json({code:'INVALID_REQUEST'});return;}await options.service.unsubscribe(current.userId,req.body.endpoint);res.status(204).end();}); return router; }
