import { Router, type Request, type Response } from 'express';
import type { IdentityRepositories } from '../../identity/application/ports.js';
import { requireActor, validMutationCsrf, type ActorContext } from '../../identity/transport/routes.js';
import { GovernanceError, type AdminCommandContext, type AdminRole, type ModerationGovernanceService } from '../application/governance.js';

const actor=(req:Request)=>(req as Request&{actor?:ActorContext}).actor;
const fail=(res:Response,error:unknown)=>{const code=error instanceof GovernanceError?error.code:'ADMIN_COMMAND_FAILED';res.status(code==='ADMIN_REQUIRED'||code==='ADMIN_ROLE_REQUIRED'?403:400).json({code});};
const command=(req:Request,current:ActorContext):AdminCommandContext|null=>{const body=req.body as {caseId?:unknown;reason?:unknown};return typeof body.caseId==='string'&&typeof body.reason==='string'&&body.reason.trim()?{...current,caseId:body.caseId,reason:body.reason.trim()}:null;};
export function adminRouter(service:ModerationGovernanceService,identity:IdentityRepositories):Router{const router=Router();const auth=requireActor(identity);router.use('/admin',auth);router.get('/admin/role',async(req,res)=>{const current=actor(req);if(!current)return;res.json({role:await service.currentRole(current.userId)});});
  const list=(loader:(a:ActorContext)=>Promise<readonly unknown[]>)=>async(req:Request,res:Response)=>{const current=actor(req);if(!current)return;try{res.json({items:await loader(current)});}catch(error){fail(res,error);}};
  router.get('/admin/reports',list((a)=>service.listReports(a)));router.get('/admin/users',list((a)=>service.listUsers(a)));router.get('/admin/audit',list((a)=>service.listAudit(a)));router.get('/admin/sessions',list((a)=>service.listSessions(a)));router.get('/admin/footprints',list((a)=>service.listFootprints(a)));
  router.post('/admin/cases',async(req,res)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}const body=req.body as {reportId?:string;targetType?:string;targetId?:string;reason?:string};if(!body.targetType||!body.targetId||!body.reason){res.status(400).json({code:'INVALID_REQUEST'});return;}try{res.status(201).json(await service.openCase(current,{...(body.reportId?{reportId:body.reportId}:{}),targetType:body.targetType,targetId:body.targetId,reason:body.reason}));}catch(error){fail(res,error);}});
  const mutate=(handler:(ctx:AdminCommandContext,target:string,body:Record<string,unknown>)=>Promise<unknown>)=>async(req:Request,res:Response)=>{const current=actor(req);if(!current)return;if(!validMutationCsrf(req,current)){res.status(403).json({code:'CSRF_ORIGIN_INVALID'});return;}const ctx=command(req,current);if(!ctx){res.status(400).json({code:'CASE_REQUIRED'});return;}try{res.json(await handler(ctx,String(req.params.id??ctx.caseId),req.body as Record<string,unknown>));}catch(error){fail(res,error);}};
  router.post('/admin/cases/:id/resolve',mutate((ctx)=>service.resolveCase(ctx)));router.post('/admin/footprints/:id/hide',mutate((ctx,id)=>service.hideFootprint(ctx,id)));router.post('/admin/footprints/:id/restore',mutate((ctx,id)=>service.restoreFootprint(ctx,id)));router.post('/admin/users/:id/suspend',mutate((ctx,id)=>service.suspendUser(ctx,id)));router.post('/admin/users/:id/role',mutate((ctx,id,body)=>service.changeRole(ctx,id,String(body.role) as AdminRole)));router.post('/admin/users/:id/revoke-sessions',mutate((ctx,id)=>service.revokeAllSessions(ctx,id)));return router;}
