import { Router, type Request, type Response } from 'express';
import { createReportInput } from '@bliver/contracts';
import { resolveSession, validMutationCsrf, type ActorContext } from '../../identity/index.js';
import type { IdentityRepositories } from '../../identity/application/ports.js';
import { ReportError } from '../domain/reports.js';
import type { CreateReport } from '../domain/reports.js';

function actorToken(request: Request): string | undefined { const bearer = request.get('authorization')?.match(/^Bearer\s+(.+)$/i)?.[1]; const cookie = request.get('cookie')?.split(';').map((part) => part.trim()).find((part) => part.startsWith('bliver_session=')); return bearer ?? (cookie ? decodeURIComponent(cookie.slice('bliver_session='.length)) : undefined); }
async function actor(request: Request, identity?: IdentityRepositories): Promise<ActorContext | null> { const value = actorToken(request); if (!value || !identity) return null; const resolved = await resolveSession(identity, value); return resolved ? { userId: resolved.user.id, sessionId: resolved.session.id, roles: resolved.user.roles, transport: request.get('authorization') ? 'bearer' : 'cookie', displayName: resolved.user.displayName } : null; }
function problem(response: Response, request: Request, status: number, code: string): void { response.status(status).type('application/problem+json').send({ type: 'about:blank', title: status === 401 ? 'Unauthorized' : 'Bad request', status, code, requestId: request.id }); }
export interface ReportRouterOptions { readonly create: CreateReport; }
export function reportRouter(options: ReportRouterOptions, identity?: IdentityRepositories): Router { const router = Router(); router.post('/reports', async (request, response) => { const parsed = createReportInput.safeParse(request.body); if (!parsed.success) { problem(response, request, 400, 'INVALID_REQUEST'); return; } const current = await actor(request, identity); if (current && !validMutationCsrf(request, current)) { problem(response, request, 403, 'CSRF_ORIGIN_INVALID'); return; } const key = request.get('idempotency-key'); try { const fingerprint = JSON.stringify(parsed.data); const report = await options.create.execute(current, { footprintId: parsed.data.footprintId, reason: parsed.data.reason, ...(parsed.data.details ? { details: parsed.data.details } : {}) }, key ? { key, fingerprint } : undefined); const result = { id: report.id, status: report.status }; response.status(201).json(result); } catch (error) { const code = error instanceof ReportError ? error.code : 'REPORT_UNAVAILABLE'; const status = code === 'AUTH_REQUIRED' ? 401 : code === 'DUPLICATE_OPEN_REPORT' ? 409 : code === 'BLOCKED' ? 403 : code === 'IDEMPOTENCY_CONFLICT' ? 409 : 400; problem(response, request, status, code); } }); return router; }
