import { randomUUID } from 'node:crypto';
import type { DatabaseClient } from '../../../platform/db/client.js';
import { GovernanceError, type AdminRole, type AuditLog, type GovernanceRepository, type ModerationCase } from '../application/governance.js';

type Row=Record<string,unknown>;
const toCase=(r:Row):ModerationCase=>({id:String(r.id),...(r.report_id?{reportId:String(r.report_id)}:{}),status:r.status as ModerationCase['status'],targetType:String(r.target_type),targetId:String(r.target_id),openedBy:String(r.opened_by),reason:String(r.reason),createdAt:new Date(String(r.created_at)),...(r.resolved_at?{resolvedAt:new Date(String(r.resolved_at))}:{})});
const toAudit=(r:Row):AuditLog=>({id:String(r.id),caseId:String(r.case_id),actorId:String(r.actor_id),action:String(r.action),targetType:String(r.target_type),targetId:String(r.target_id),reason:String(r.reason),before:(r.before_summary as Record<string,unknown>)??{},after:(r.after_summary as Record<string,unknown>)??{},createdAt:new Date(String(r.created_at))});

export function createPostgresGovernanceRepository(db:DatabaseClient):GovernanceRepository{return{
  async role(userId){const r=await db.query<Row>('SELECT role FROM admin_roles WHERE user_id=$1',[userId]);return (r.rows[0]?.role as AdminRole|undefined)??null;},
  async openCase(item){await db.query('INSERT INTO moderation_cases(id,report_id,status,target_type,target_id,opened_by,reason,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[item.id,item.reportId??null,item.status,item.targetType,item.targetId,item.openedBy,item.reason,item.createdAt]);return item;},
  async findCase(id){const r=await db.query<Row>('SELECT * FROM moderation_cases WHERE id=$1',[id]);return r.rows[0]?toCase(r.rows[0]):null;},
  async commit(input){return db.transaction(async(client)=>{const role=await client.query<Row>('SELECT role FROM admin_roles WHERE user_id=$1 FOR SHARE',[input.context.userId]);if(!role.rows[0]||(input.requiredRole==='admin'&&role.rows[0].role!=='admin'))throw new GovernanceError('ADMIN_REQUIRED');const c=await client.query<Row>('SELECT * FROM moderation_cases WHERE id=$1 FOR UPDATE',[input.context.caseId]);if(!c.rows[0])throw new GovernanceError('CASE_REQUIRED');if(String(c.rows[0].status)!=='open')throw new GovernanceError('CASE_CLOSED');if(input.action!=='resolve_case'&&(String(c.rows[0].target_type)!==input.targetType||String(c.rows[0].target_id)!==input.targetId))throw new GovernanceError('INVALID_TARGET');let before:Record<string,unknown>={};let after:Record<string,unknown>={};
    if(input.action==='resolve_case'){before={status:c.rows[0].status};const changed=await client.query<Row>("UPDATE moderation_cases SET status='resolved',resolved_at=now() WHERE id=$1 AND status='open' RETURNING id",[input.context.caseId]);if(!changed.rowCount)throw new GovernanceError('CASE_CLOSED');after={status:'resolved'};}
    else if(input.action==='hide_footprint'||input.action==='restore_footprint'){const current=await client.query<Row>('SELECT visibility,moderation_hidden_at FROM footprints WHERE id=$1 FOR UPDATE',[input.targetId]);if(!current.rows[0])throw new GovernanceError('INVALID_TARGET');before=current.rows[0];const changed=input.action==='hide_footprint'?await client.query<Row>('UPDATE footprints SET moderation_hidden_at=now() WHERE id=$1 RETURNING id',[input.targetId]):await client.query<Row>('UPDATE footprints SET moderation_hidden_at=NULL WHERE id=$1 RETURNING id',[input.targetId]);if(!changed.rowCount)throw new GovernanceError('INVALID_TARGET');after={hidden:input.action==='hide_footprint'};}
    else if(input.action==='suspend_user'){const current=await client.query<Row>('SELECT suspended_at FROM identity_users WHERE id=$1 FOR UPDATE',[input.targetId]);if(!current.rows[0])throw new GovernanceError('INVALID_TARGET');before=current.rows[0];const changed=await client.query<Row>('UPDATE identity_users SET suspended_at=now() WHERE id=$1 RETURNING id',[input.targetId]);if(!changed.rowCount)throw new GovernanceError('INVALID_TARGET');await client.query('UPDATE identity_sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[input.targetId]);after={suspended:true};}
    else if(input.action==='change_role'){const current=await client.query<Row>('SELECT role FROM admin_roles WHERE user_id=$1',[input.targetId]);const user=await client.query<Row>('SELECT id FROM identity_users WHERE id=$1',[input.targetId]);if(!user.rowCount)throw new GovernanceError('INVALID_TARGET');before=current.rows[0]??{};await client.query('INSERT INTO admin_roles(user_id,role,granted_by) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET role=$2,granted_by=$3,created_at=now()',[input.targetId,input.value,input.context.userId]);after={role:input.value};}
    else if(input.action==='revoke_sessions'){const user=await client.query<Row>('SELECT id FROM identity_users WHERE id=$1',[input.targetId]);if(!user.rowCount)throw new GovernanceError('INVALID_TARGET');await client.query('UPDATE identity_sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[input.targetId]);after={sessionsRevoked:true};}
    await client.query('INSERT INTO moderation_actions(id,case_id,action,actor_id,target_id,reason,before_summary,after_summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[input.id,input.context.caseId,input.action,input.context.userId,input.targetId,input.context.reason,JSON.stringify(before),JSON.stringify(after)]);
    await client.query('INSERT INTO audit_logs(id,case_id,actor_id,action,target_type,target_id,reason,before_summary,after_summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[input.id,input.context.caseId,input.context.userId,input.action,input.targetType,input.targetId,input.context.reason,JSON.stringify(before),JSON.stringify(after)]);
    const recipient=input.eventType==='ReportResolved'&&c.rows[0].report_id?(await client.query<Row>('SELECT reporter_id FROM reports WHERE id=$1',[c.rows[0].report_id])).rows[0]?.reporter_id:undefined;await client.query('INSERT INTO platform.outbox_events(id,type,aggregate_id,payload) VALUES($1,$2,$3,$4)',[randomUUID(),input.eventType,input.targetId,JSON.stringify({actorId:input.context.userId,targetId:input.targetId,caseId:input.context.caseId,...(recipient?{recipientId:String(recipient)}:{})})]);
    return{id:input.id,caseId:input.context.caseId,actorId:input.context.userId,action:input.action,targetType:input.targetType,targetId:input.targetId,reason:input.context.reason,before,after,createdAt:new Date()};});},
  async hasCaseAccess(userId,footprintId){const r=await db.query<Row>("SELECT 1 FROM admin_roles ar JOIN moderation_cases mc ON mc.target_type='footprint' AND mc.target_id=$2 AND mc.status='open' WHERE ar.user_id=$1",[userId,footprintId]);return Boolean(r.rowCount);},
  async reports(){return(await db.query<Row>('SELECT * FROM reports ORDER BY created_at DESC LIMIT 200')).rows;},
  async users(){return(await db.query<Row>('SELECT u.id,u.username,u.display_name,u.suspended_at,ar.role FROM identity_users u LEFT JOIN admin_roles ar ON ar.user_id=u.id ORDER BY u.created_at DESC LIMIT 200')).rows;},
  async audit(){return(await db.query<Row>('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 200')).rows.map(toAudit);},
  async sessions(){return(await db.query<Row>('SELECT id,user_id,created_at,last_seen_at,revoked_at FROM identity_sessions ORDER BY created_at DESC LIMIT 200')).rows;},
  async footprints(){return(await db.query<Row>('SELECT id,author_id,visibility,published_at,moderation_hidden_at FROM footprints ORDER BY published_at DESC LIMIT 200')).rows;}
};}
