import { useEffect, useMemo, useState } from 'react';
import type { PublishFootprintRequest } from '@bliver/contracts';
import { Button, Surface } from '@bliver/ui';
import './footprints.css';
import { clearFootprintDraft, loadFootprintDraft, saveFootprintDraft } from '../../platform/drafts.js';

type PublishInput = Omit<PublishFootprintRequest, 'mediaAssetIds'> & { readonly mediaAssetIds?: readonly string[] };
export interface PublishFootprintRouteProps { readonly initialPoint?: { readonly lat: number; readonly lng: number }; readonly signUpload: (file: File) => Promise<unknown>; readonly publish: (input: PublishInput) => Promise<void>; }
export function PublishFootprintRoute({ initialPoint, signUpload, publish }: PublishFootprintRouteProps) {
  const recovered = useMemo(() => loadFootprintDraft(), []);
  const [message, setMessage] = useState(recovered?.message ?? ''); const [visibility, setVisibility] = useState<'public' | 'friends' | 'private'>(recovered?.visibility ?? 'public'); const [locationPrecision, setLocationPrecision] = useState<'precise' | 'approximate'>(recovered?.locationPrecision ?? 'approximate'); const [file, setFile] = useState<File>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  useEffect(() => { if (message || recovered) saveFootprintDraft({ message, visibility, locationPrecision }); }, [locationPrecision, message, recovered, visibility]);
  const submit = async (): Promise<void> => { setError(undefined); if (!message.trim()) { setError('Write a message before publishing.'); return; } if (!initialPoint) { setError('Select a location before publishing.'); return; } setBusy(true); try { let mediaAssetIds: string[] = []; if (file) { const signed = await signUpload(file); const assetId = typeof signed === 'object' && signed !== null && 'assetId' in signed && typeof signed.assetId === 'string' ? signed.assetId : undefined; if (assetId) mediaAssetIds = [assetId]; } await publish({ message: message.trim(), privatePoint: initialPoint, visibility, locationPrecision, mediaAssetIds }); clearFootprintDraft(); } catch { setError(file ? 'Upload failed. Try again.' : 'Publish failed. Try again.'); } finally { setBusy(false); } };
  return <section className="publish-route"><Surface><h1>Publish a footprint</h1><label htmlFor="message">Message</label><textarea id="message" value={message} onChange={(event) => setMessage(event.target.value)} rows={4} /><label htmlFor="visibility">Who can see it</label><select id="visibility" value={visibility} onChange={(event) => setVisibility(event.target.value as typeof visibility)}><option value="public">Everyone</option><option value="friends">Friends</option><option value="private">Only me</option></select><label htmlFor="precision">Location precision</label><select id="precision" value={locationPrecision} onChange={(event) => setLocationPrecision(event.target.value as typeof locationPrecision)}><option value="approximate">Approximate</option><option value="precise">Precise</option></select><label htmlFor="photo">Photo (optional)</label><input id="photo" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => setFile(event.target.files?.[0])} />{error ? <p role="alert">{error}</p> : null}<Button onClick={() => void submit()} disabled={busy}>{busy ? 'Publishing...' : 'Publish footprint'}</Button></Surface></section>;
}
