import request from 'supertest';
import { describe, expect, it, vi } from 'vitest';
import { createFootprintId, createUserId } from '@bliver/domain';
import { createConfig } from '../../../../bootstrap/config.js';
import { createApp } from '../../../../http/app.js';
import { createMemoryIdentityRepositories } from '../../../identity/application/memory-repositories.js';
import { FootprintVisibilityPolicy, MapFootprintQuery, createMemoryMapFootprintRepository } from '../../../footprints/index.js';
import { createMemoryDiscoveryRepository, DiscoveryQueryService, type DiscoveryEntry } from '../../index.js';
import { InteractionService, createMemoryInteractionRepository } from '../../../interactions/index.js';

const config = createConfig({ NODE_ENV: 'test', DEPLOY_ENV: 'test', RELEASE_SHA: 'test', DATABASE_URL: 'postgresql://test:test@localhost:5432/test', SESSION_SECRET: 'test-session-secret-that-is-long-enough-1234' });
function discoveryApp() { const owner = createUserId(); const entry: DiscoveryEntry = { id: createFootprintId(), authorId: owner, author: { name: 'Lin' }, displayPoint: { lat: 31, lng: 121 }, visibility: 'public', locationPrecision: 'approximate', message: 'River', publishedAt: new Date('2026-07-15T08:00:00.000Z'), discoveryExpiresAt: new Date('2099-07-15T08:00:00.000Z'), regionId: 'r', countryCode: 'CN' }; const policy = new FootprintVisibilityPolicy({ records: { async findById() { return entry; } }, friendships: { async areAcceptedFriends() { return false; } }, blocks: { async isEitherBlocked() { return false; } }, moderation: { async hasCaseAccess() { return false; } }, now: () => new Date('2026-07-15T09:00:00.000Z') }); const map = new MapFootprintQuery({ repository: createMemoryMapFootprintRepository([entry]), policy }); const activity = new DiscoveryQueryService({ repository: createMemoryDiscoveryRepository([entry]), policy, cursorSecret: config.sessionSecret }); return { app: createApp({ config, map: { query: map }, discovery: { activity, map } }), entry }; }
describe('discovery and interaction REST transport', () => {
  it('returns the exact same privacy DTO from map and activity', async () => { const { app } = discoveryApp(); const map = await request(app).get('/api/v1/discovery/map?west=120&south=30&east=122&north=32').expect(200); const activity = await request(app).get('/api/v1/activity?scope=global&relationship=all&content=all&limit=20').expect(200); expect(activity.body.items).toEqual(map.body.items); expect(activity.body.resolvedScope).toBe('global'); });
  it('requires auth for commands and accepts reaction, two-level comments, and report intake', async () => { const identity = createMemoryIdentityRepositories(); const app = createApp({ config, identity }); const footprintId = createFootprintId(); await request(app).post(`/api/v1/footprints/${footprintId}/reactions`).send({ emoji: 'heart' }).expect(401); await request(app).post('/api/v1/reports').send({ footprintId, reason: 'spam' }).expect(401); await request(app).post('/api/v1/auth/register').send({ username: 'interactionuser', password: 'password-123' }).expect(201); const login = await request(app).post('/api/v1/auth/login').send({ username: 'interactionuser', password: 'password-123', platform: 'capacitor' }).expect(200); const auth = { Authorization: `Bearer ${login.body.accessToken as string}` }; await request(app).post(`/api/v1/footprints/${footprintId}/reactions`).set(auth).send({ emoji: 'heart' }).expect(200); const comment = await request(app).post(`/api/v1/footprints/${footprintId}/comments`).set(auth).send({ content: 'hello' }).expect(201); await request(app).post(`/api/v1/footprints/${footprintId}/comments/${String(comment.body.id)}/replies`).set(auth).send({ content: 'reply' }).expect(201); await request(app).post('/api/v1/reports').set(auth).send({ footprintId, reason: 'spam' }).expect(201); await request(app).post('/api/v1/reports').set(auth).send({ footprintId, reason: 'spam' }).expect(409); });
  it('checks privacy before exposing private conversation reads', async () => { const service = new InteractionService(createMemoryInteractionRepository(), { async canInteract() { return false; }, async canRead() { return false; }, async isBlocked() { return true; }, async footprintOwner() { return null; } }); const app = createApp({ config, interactions: { service } }); const footprintId = createFootprintId(); await request(app).get(`/api/v1/footprints/${footprintId}/comments`).expect(403); await request(app).get(`/api/v1/footprints/${footprintId}/reactions`).expect(403); });
  it('replays durable command idempotency responses for the same actor and key', async () => { const identity = createMemoryIdentityRepositories(); const app = createApp({ config, identity }); const footprintId = createFootprintId(); await request(app).post('/api/v1/auth/register').send({ username: 'idemuser', password: 'password-123' }).expect(201); const login = await request(app).post('/api/v1/auth/login').send({ username: 'idemuser', password: 'password-123', platform: 'capacitor' }).expect(200); const auth = { Authorization: `Bearer ${login.body.accessToken as string}`, 'Idempotency-Key': 'report-key' }; const first = await request(app).post('/api/v1/reports').set(auth).send({ footprintId, reason: 'spam' }).expect(201); const second = await request(app).post('/api/v1/reports').set(auth).send({ footprintId, reason: 'spam' }).expect(201); expect(second.body).toEqual(first.body); });
  it('passes authenticated regional context into smart Activity resolution', async () => { const identity = createMemoryIdentityRepositories(); const execute = vi.fn(async () => ({ items: [], resolvedScope: 'country' as const })); const app = createApp({ config, identity, discovery: { activity: { execute } as unknown as DiscoveryQueryService, regionForActor: async (actor) => actor ? { regionId: 'region-a', countryCode: 'CN' } : {} } }); await request(app).post('/api/v1/auth/register').send({ username: 'regionuser', password: 'password-123' }).expect(201); const login = await request(app).post('/api/v1/auth/login').send({ username: 'regionuser', password: 'password-123', platform: 'capacitor' }).expect(200); await request(app).get('/api/v1/activity?scope=smart&relationship=all&content=all&limit=20').set('Authorization', `Bearer ${login.body.accessToken as string}`).expect(200); expect(execute).toHaveBeenCalledWith(expect.objectContaining({ regionId: 'region-a', countryCode: 'CN' })); });
});
