import type { DatabaseClient } from '../../../platform/db/client.js';
import type { NotificationPreferences,NotificationRecord,NotificationRepository } from '../domain/types.js';
type Row=Record<string,unknown>;const defaults:NotificationPreferences={reactions:true,comments:true,social:true,messages:true,moderation:true,push:false};
const map=(row:Row):NotificationRecord=>({id:String(row.id),recipientId:String(row.recipient_id),type:String(row.type),...(row.actor_id?{actorId:String(row.actor_id)}:{}),targetType:String(row.target_type),targetId:String(row.target_id),payload:(row.payload as Record<string,unknown>)??{},createdAt:new Date(String(row.created_at)),dedupeKey:String(row.dedupe_key),readAt:row.read_at?new Date(String(row.read_at)):null});
export function createPostgresNotificationRepository(db:DatabaseClient):NotificationRepository{return{
  async create(item){await db.query('INSERT INTO notifications(id,recipient_id,type,actor_id,target_type,target_id,payload,dedupe_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING',[item.id,item.recipientId,item.type,item.actorId??null,item.targetType,item.targetId,JSON.stringify(item.payload),item.dedupeKey]);},
  async findByDedupe(recipientId,key){const result=await db.query<Row>('SELECT * FROM notifications WHERE recipient_id=$1 AND dedupe_key=$2',[recipientId,key]);return result.rows[0]?map(result.rows[0]):null;},
  async list(recipientId,cursor){const result=await db.query<Row>('SELECT * FROM notifications WHERE recipient_id=$1 AND ($2::timestamptz IS NULL OR created_at<$2) ORDER BY created_at DESC,id DESC LIMIT 50',[recipientId,cursor??null]);return result.rows.map(map);},
  async unreadCount(recipientId){const result=await db.query<Row>('SELECT count(*)::int AS count FROM notifications WHERE recipient_id=$1 AND read_at IS NULL',[recipientId]);return Number(result.rows[0]?.count??0);},
  async markRead(recipientId,id){await db.query('UPDATE notifications SET read_at=now() WHERE recipient_id=$1 AND id=$2',[recipientId,id]);},async markAllRead(recipientId){await db.query('UPDATE notifications SET read_at=now() WHERE recipient_id=$1 AND read_at IS NULL',[recipientId]);},
  async preferences(userId){const result=await db.query<Row>('SELECT reactions,comments,social,messages,moderation,push FROM notification_preferences WHERE user_id=$1',[userId]);const row=result.rows[0];return row?{reactions:Boolean(row.reactions),comments:Boolean(row.comments),social:Boolean(row.social),messages:Boolean(row.messages),moderation:Boolean(row.moderation),push:Boolean(row.push)}:defaults;},
  async setPreferences(userId,input){const current=await this.preferences(userId);const value={...current,...input};await db.query('INSERT INTO notification_preferences(user_id,reactions,comments,social,messages,moderation,push) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET reactions=$2,comments=$3,social=$4,messages=$5,moderation=$6,push=$7,updated_at=now()',[userId,value.reactions,value.comments,value.social,value.messages,value.moderation,value.push]);return value;},
  async addSubscription(item){await db.transaction(async(client)=>{const owner=await client.query<Row>('SELECT user_id FROM push_subscriptions WHERE endpoint=$1 FOR UPDATE',[item.endpoint]);if(owner.rows[0]&&String(owner.rows[0].user_id)!==item.userId)throw new Error('PUSH_SUBSCRIPTION_OWNED');const saved=await client.query<Row>('INSERT INTO push_subscriptions(id,user_id,endpoint,p256dh,auth) VALUES($1,$2,$3,$4,$5) ON CONFLICT(endpoint) DO UPDATE SET p256dh=$4,auth=$5,updated_at=now() WHERE push_subscriptions.user_id=$2 RETURNING id',[item.id,item.userId,item.endpoint,item.p256dh,item.auth]);if(!saved.rowCount)throw new Error('PUSH_SUBSCRIPTION_OWNED');});},
  async removeSubscription(userId,endpoint){await db.query('DELETE FROM push_subscriptions WHERE user_id=$1 AND endpoint=$2',[userId,endpoint]);},async subscriptions(userId){const result=await db.query<Row>('SELECT * FROM push_subscriptions WHERE user_id=$1',[userId]);return result.rows.map((row)=>({id:String(row.id),userId:String(row.user_id),endpoint:String(row.endpoint),p256dh:String(row.p256dh),auth:String(row.auth)}));},
  async recordDeliveryAttempt(input){await db.query('INSERT INTO delivery_attempts(id,notification_id,channel,attempt,status,error) VALUES($1,$2,$3,$4,$5,$6)',[input.id,input.notificationId,input.channel,input.attempt,input.status,input.error??null]);},
};}
