import { randomUUID } from 'node:crypto';
import type { ActorContext } from '../../identity/index.js';

export type AdminRole = 'moderator' | 'admin';
export type CaseDisposition = 'resolved' | 'dismissed';
export interface AdminCommandContext extends ActorContext { readonly caseId: string; readonly reason: string; }
export interface ModerationCase { readonly id: string; readonly reportId?: string; readonly status: 'open'|'resolved'|'dismissed'; readonly targetType: string; readonly targetId: string; readonly openedBy: string; readonly reason: string; readonly createdAt: Date; readonly resolvedAt?: Date; }
export interface AuditLog { readonly id:string; readonly caseId:string; readonly actorId:string; readonly action:string; readonly targetType:string; readonly targetId:string; readonly reason:string; readonly before:Record<string,unknown>; readonly after:Record<string,unknown>; readonly createdAt:Date; }
export interface GovernanceMutation { readonly id:string; readonly action:'resolve_case'|'hide_footprint'|'restore_footprint'|'suspend_user'|'change_role'|'revoke_sessions'; readonly context:AdminCommandContext; readonly targetType:string; readonly targetId:string; readonly value?:string; readonly eventType:string; readonly requiredRole:AdminRole; }
export interface GovernanceRepository { role(userId:string):Promise<AdminRole|null>; openCase(input:ModerationCase):Promise<ModerationCase>; findCase(id:string):Promise<ModerationCase|null>; commit(input:GovernanceMutation):Promise<AuditLog>; hasCaseAccess(userId:string,footprintId:string):Promise<boolean>; reports():Promise<readonly unknown[]>; users():Promise<readonly unknown[]>; audit():Promise<readonly AuditLog[]>; sessions():Promise<readonly unknown[]>; footprints():Promise<readonly unknown[]>; }
export class GovernanceError extends Error { constructor(readonly code:'ADMIN_REQUIRED'|'CASE_REQUIRED'|'CASE_CLOSED'|'ADMIN_ROLE_REQUIRED'|'INVALID_TARGET'){super(code);} }
export class ModerationGovernanceService {
  constructor(private readonly repository:GovernanceRepository){}
  async currentRole(userId:string):Promise<AdminRole|null>{return this.repository.role(userId);}
  async openCase(actor:ActorContext,input:{reportId?:string;targetType:string;targetId:string;reason:string}):Promise<ModerationCase>{await this.requireRole(actor,'moderator');return this.repository.openCase({id:randomUUID(),...(input.reportId?{reportId:input.reportId}:{}),status:'open',targetType:input.targetType,targetId:input.targetId,openedBy:actor.userId,reason:input.reason,createdAt:new Date()});}
  async resolveCase(context:AdminCommandContext,disposition:CaseDisposition='resolved'):Promise<AuditLog>{if(disposition!=='resolved'&&disposition!=='dismissed')throw new GovernanceError('INVALID_TARGET');return this.execute(context,'resolve_case','case',context.caseId,'ReportResolved',disposition);}
  async hideFootprint(context:AdminCommandContext,footprintId:string):Promise<AuditLog>{return this.execute(context,'hide_footprint','footprint',footprintId,'FootprintHidden');}
  async restoreFootprint(context:AdminCommandContext,footprintId:string):Promise<AuditLog>{return this.execute(context,'restore_footprint','footprint',footprintId,'FootprintRestored');}
  async suspendUser(context:AdminCommandContext,userId:string):Promise<AuditLog>{return this.execute(context,'suspend_user','user',userId,'UserSuspended');}
  async changeRole(context:AdminCommandContext,userId:string,role:AdminRole):Promise<AuditLog>{await this.requireRole(context,'admin');return this.execute(context,'change_role','user',userId,'RoleChanged',role);}
  async revokeAllSessions(context:AdminCommandContext,userId:string):Promise<AuditLog>{return this.execute(context,'revoke_sessions','user',userId,'SessionsRevoked');}
  async hasCaseAccess(userId:string,footprintId:string){return this.repository.hasCaseAccess(userId,footprintId);}
  async listReports(actor:ActorContext){await this.requireRole(actor,'moderator');return this.repository.reports();} async listUsers(actor:ActorContext){await this.requireRole(actor,'moderator');return this.repository.users();} async listAudit(actor:ActorContext){await this.requireRole(actor,'moderator');return this.repository.audit();} async listSessions(actor:ActorContext){await this.requireRole(actor,'admin');return this.repository.sessions();} async listFootprints(actor:ActorContext){await this.requireRole(actor,'moderator');return this.repository.footprints();}
  private async execute(context:AdminCommandContext,action:GovernanceMutation['action'],targetType:string,targetId:string,eventType:string,value?:string){const requiredRole:AdminRole=action==='change_role'?'admin':'moderator';await this.requireRole(context,requiredRole);const moderationCase=await this.repository.findCase(context.caseId);if(!moderationCase)throw new GovernanceError('CASE_REQUIRED');if(moderationCase.status!=='open'&&action!=='resolve_case')throw new GovernanceError('CASE_CLOSED');if(action!=='resolve_case'&&(moderationCase.targetType!==targetType||moderationCase.targetId!==targetId))throw new GovernanceError('INVALID_TARGET');return this.repository.commit({id:randomUUID(),action,context,targetType,targetId,...(value?{value}:{}),eventType,requiredRole});}
  private async requireRole(actor:ActorContext,required:AdminRole){const role=await this.repository.role(actor.userId);if(!role)throw new GovernanceError('ADMIN_REQUIRED');if(required==='admin'&&role!=='admin')throw new GovernanceError('ADMIN_ROLE_REQUIRED');}
}
