import type { FootprintId, UserId } from '@bliver/domain';
import type { DatabaseClient } from '../../../platform/db/client.js';
import type { MemoryProjectionRepository, MemoryRecordSource } from '../domain/ports.js';
import type { MemoryVisitorDto } from '../domain/ports.js';

type Row = Record<string, unknown>;
export function createPostgresMemoryRepository(db: DatabaseClient): MemoryProjectionRepository {
  const source: MemoryRecordSource = {
    async listByOwner(ownerId) { const result = await db.query<Row>(`SELECT f.id, f.author_id, u.display_name AS author_name, ST_Y(f.display_point::geometry) AS display_lat, ST_X(f.display_point::geometry) AS display_lng, f.visibility, f.location_precision, f.message, f.published_at, f.discovery_expires_at FROM footprints f JOIN identity_users u ON u.id=f.author_id WHERE f.author_id=$1 ORDER BY f.published_at DESC, f.id DESC`, [ownerId]); return result.rows.map((row) => ({ id: String(row.id) as FootprintId, authorId: String(row.author_id) as UserId, author: { name: String(row.author_name) }, displayPoint: { lat: Number(row.display_lat), lng: Number(row.display_lng) }, visibility: row.visibility as 'public' | 'friends' | 'private', locationPrecision: row.location_precision as 'precise' | 'approximate', publishedAt: new Date(String(row.published_at)), discoveryExpiresAt: row.discovery_expires_at ? new Date(String(row.discovery_expires_at)) : null, message: String(row.message) })); },
    async findById(id) { const result = await db.query<Row>('SELECT f.id, f.author_id, u.display_name AS author_name, ST_Y(f.display_point::geometry) AS display_lat, ST_X(f.display_point::geometry) AS display_lng, f.visibility, f.location_precision, f.message, f.published_at, f.discovery_expires_at FROM footprints f JOIN identity_users u ON u.id=f.author_id WHERE f.id=$1', [id]); const row=result.rows[0]; return row ? { id: String(row.id) as FootprintId, authorId: String(row.author_id) as UserId, author: { name: String(row.author_name) }, displayPoint: { lat:Number(row.display_lat), lng:Number(row.display_lng) }, visibility: row.visibility as 'public'|'friends'|'private', locationPrecision: row.location_precision as 'precise'|'approximate', publishedAt:new Date(String(row.published_at)), discoveryExpiresAt:row.discovery_expires_at?new Date(String(row.discovery_expires_at)):null, message:String(row.message) } : null; },
  };
  return { ...source, async upsertFootprint() {}, async markEvent(eventId) { const result = await db.query<Row>('INSERT INTO platform.processed_events (event_id) VALUES ($1) ON CONFLICT DO NOTHING RETURNING event_id', [eventId]); return Boolean(result.rowCount); }, async recordVisitor(ownerId, visitorId) { await db.query('INSERT INTO profile_visitors(owner_id,visitor_id) VALUES($1,$2) ON CONFLICT(owner_id,visitor_id) DO UPDATE SET last_visited_at=now(), visit_count=profile_visitors.visit_count+1', [ownerId, visitorId]); } };
}
