export interface PlaceResult { readonly id: string; readonly name: string; readonly lat: number; readonly lng: number; readonly countryCode?: string; }
export interface GeographyPorts { geocode(input: { readonly latitude: number; readonly longitude: number }): Promise<{ readonly place: PlaceResult | null; readonly region: { readonly id: string; readonly name: string } | null }>; searchPlaces(query: string): Promise<ReadonlyArray<PlaceResult>>; weather(input: { readonly latitude: number; readonly longitude: number }): Promise<Record<string, unknown> | null>; }
export interface GeographyProviderOptions { readonly fetch?: typeof fetch; readonly timeoutMs?: number; readonly baseUrl?: string; }
async function bounded<T>(task: Promise<T>, timeoutMs: number): Promise<T> { return Promise.race([task, new Promise<T>((_, reject) => setTimeout(() => reject(new Error('provider timeout')), timeoutMs))]); }
export function createNominatimGeography(options: GeographyProviderOptions = {}): GeographyPorts {
  const fetcher = options.fetch ?? fetch; const timeout = options.timeoutMs ?? 2_000; const base = options.baseUrl ?? 'https://nominatim.openstreetmap.org';
  return {
    async geocode(input) { try { const response = await bounded(fetcher(`${base}/reverse?format=jsonv2&lat=${input.latitude}&lon=${input.longitude}`, { headers: { 'user-agent': 'bliver-v2/1.0' } }), timeout); if (!response.ok) return { place: null, region: null }; const body = await response.json() as { place_id?: number; display_name?: string; lat?: string; lon?: string; address?: { country_code?: string; state?: string } }; return { place: body.place_id && body.display_name && body.lat && body.lon ? { id: String(body.place_id), name: body.display_name, lat: Number(body.lat), lng: Number(body.lon), ...(body.address?.country_code ? { countryCode: body.address.country_code.toUpperCase() } : {}) } : null, region: body.address?.state ? { id: body.address.state, name: body.address.state } : null }; } catch { return { place: null, region: null }; } },
    async searchPlaces(query) { try { const response = await bounded(fetcher(`${base}/search?format=jsonv2&limit=8&q=${encodeURIComponent(query)}`, { headers: { 'user-agent': 'bliver-v2/1.0' } }), timeout); if (!response.ok) return []; const rows = await response.json() as Array<{ place_id?: number; display_name?: string; lat?: string; lon?: string }>; return rows.flatMap((row) => row.place_id && row.display_name && row.lat && row.lon ? [{ id: String(row.place_id), name: row.display_name, lat: Number(row.lat), lng: Number(row.lon) }] : []); } catch { return []; } },
    async weather() { return null; },
  };
}
