import { Router, type Request, type Response } from 'express';
import { addCommentInput, addReactionInput } from '@bliver/contracts';
import { resolveSession, type ActorContext } from '../../identity/index.js';
import type { IdentityRepositories } from '../../identity/application/ports.js';
import { InteractionError, type Comment, type Reaction } from '../domain/model.js';
import type { InteractionService } from '../application/service.js';
import { createMemoryCommandIdempotencyRepository, IdempotencyConflictError } from '../../../platform/idempotency/index.js';
import type { CommandIdempotencyRepository } from '../../../platform/idempotency/index.js';

function actorToken(request: Request): string | undefined { const bearer = request.get('authorization')?.match(/^Bearer\s+(.+)$/i)?.[1]; const cookie = request.get('cookie')?.split(';').map((part) => part.trim()).find((part) => part.startsWith('bliver_session=')); return bearer ?? (cookie ? decodeURIComponent(cookie.slice('bliver_session='.length)) : undefined); }
async function actor(request: Request, identity?: IdentityRepositories): Promise<ActorContext | null> { const value = actorToken(request); if (!value || !identity) return null; const resolved = await resolveSession(identity, value); return resolved ? { userId: resolved.user.id, sessionId: resolved.session.id, roles: resolved.user.roles, transport: request.get('authorization') ? 'bearer' : 'cookie' } : null; }
function problem(response: Response, request: Request, status: number, code: string): void { response.status(status).type('application/problem+json').send({ type: 'about:blank', title: status === 401 ? 'Unauthorized' : 'Bad request', status, code, requestId: request.id }); }
function mapError(error: unknown): number { return error instanceof InteractionError && error.code === 'AUTH_REQUIRED' ? 401 : error instanceof InteractionError && ['BLOCKED', 'COMMENT_FORBIDDEN'].includes(error.code) ? 403 : error instanceof InteractionError && ['COMMENT_DEPTH_INVALID', 'COMMENT_PARENT_INVALID', 'REACTION_INVALID'].includes(error.code) ? 400 : 409; }
function reactionDto(item: Reaction) { return { emoji: item.emoji, actorId: item.actorId, createdAt: item.createdAt.toISOString() }; }
function commentDto(item: Comment) { return { id: item.id, footprintId: item.footprintId, author: { id: item.authorId, name: item.authorName }, content: item.content, parentCommentId: item.parentCommentId, createdAt: item.createdAt.toISOString(), ...(item.deletedAt ? { deletedAt: item.deletedAt.toISOString() } : {}) }; }

export interface InteractionRouterOptions { readonly service: InteractionService; readonly idempotency?: CommandIdempotencyRepository; }
export function interactionRouter(options: InteractionRouterOptions, identity?: IdentityRepositories, idempotency: CommandIdempotencyRepository = options.idempotency ?? createMemoryCommandIdempotencyRepository()): Router {
  const router = Router();
  router.get('/footprints/:footprintId/reactions', async (request, response) => { try { const current = await actor(request, identity); const limit = Math.max(1, Math.min(100, Number(request.query.limit ?? 100))); response.json({ items: (await options.service.listReactions(current, String(request.params.footprintId))).slice(0, limit).map(reactionDto) }); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : 'INVALID_REQUEST'); } });
  router.post('/footprints/:footprintId/reactions', async (request, response) => { const current = await actor(request, identity); const key = request.get('idempotency-key'); const parsed = addReactionInput.safeParse(request.body); if (!parsed.success) { problem(response, request, 400, 'INVALID_REQUEST'); return; } try { const scope = 'interaction.reaction'; const fingerprint = JSON.stringify({ footprintId: request.params.footprintId, emoji: parsed.data.emoji }); const prior = current && key ? await idempotency.find(current.userId, scope, key) : null; if (prior) { if (prior.fingerprint !== fingerprint) throw new IdempotencyConflictError(); response.status(200).json(prior.response); return; } const result = reactionDto(await options.service.addReaction(current, String(request.params.footprintId), parsed.data.emoji)); if (current && key) await idempotency.save(current.userId, scope, key, fingerprint, result); response.status(200).json(result); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : error instanceof IdempotencyConflictError ? error.code : 'INTERACTION_UNAVAILABLE'); } });
  router.delete('/footprints/:footprintId/reactions', async (request, response) => { try { await options.service.removeReaction(await actor(request, identity), String(request.params.footprintId)); response.status(204).end(); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : 'INTERACTION_UNAVAILABLE'); } });
  router.get('/footprints/:footprintId/comments', async (request, response) => { try { const current = await actor(request, identity); const limit = Math.max(1, Math.min(100, Number(request.query.limit ?? 50))); const comments = await options.service.listComments(current, String(request.params.footprintId)); const top = comments.filter((item) => !item.parentCommentId).slice(0, limit).map((item) => ({ ...commentDto(item), replies: comments.filter((child) => child.parentCommentId === item.id).slice(0, 100).map(commentDto) })); response.json({ items: top }); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : 'INVALID_REQUEST'); } });
  router.post('/footprints/:footprintId/comments', async (request, response) => { const parsed = addCommentInput.safeParse({ ...request.body, footprintId: String(request.params.footprintId) }); if (!parsed.success) { problem(response, request, 400, 'INVALID_REQUEST'); return; } const current = await actor(request, identity); const key = request.get('idempotency-key'); try { const scope = 'interaction.comment'; const fingerprint = JSON.stringify(parsed.data); const prior = current && key ? await idempotency.find(current.userId, scope, key) : null; if (prior) { if (prior.fingerprint !== fingerprint) throw new IdempotencyConflictError(); response.status(201).json(prior.response); return; } const result = commentDto(await options.service.addComment(current, parsed.data)); if (current && key) await idempotency.save(current.userId, scope, key, fingerprint, result); response.status(201).json(result); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : error instanceof IdempotencyConflictError ? error.code : 'INTERACTION_UNAVAILABLE'); } });
  router.post('/footprints/:footprintId/comments/:commentId/replies', async (request, response) => { const content = typeof request.body?.content === 'string' ? request.body.content : ''; const current = await actor(request, identity); const key = request.get('idempotency-key'); try { const scope = 'interaction.reply'; const fingerprint = JSON.stringify({ footprintId: request.params.footprintId, parentCommentId: request.params.commentId, content }); const prior = current && key ? await idempotency.find(current.userId, scope, key) : null; if (prior) { if (prior.fingerprint !== fingerprint) throw new IdempotencyConflictError(); response.status(201).json(prior.response); return; } const result = commentDto(await options.service.addReply(current, String(request.params.footprintId), String(request.params.commentId), content)); if (current && key) await idempotency.save(current.userId, scope, key, fingerprint, result); response.status(201).json(result); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : error instanceof IdempotencyConflictError ? error.code : 'INTERACTION_UNAVAILABLE'); } });
  router.delete('/comments/:commentId', async (request, response) => { try { await options.service.deleteComment(await actor(request, identity), String(request.params.commentId)); response.status(204).end(); } catch (error) { problem(response, request, mapError(error), error instanceof InteractionError ? error.code : 'INTERACTION_UNAVAILABLE'); } });
  return router;
}
