import { describe, expect, it } from 'vitest';
import { FootprintVisibilityPolicy, type FootprintPolicyInput } from '../../../footprints/domain/visibility-policy.js';
import { AuthorizedMemoryQuery, InMemoryVisitorSource } from '../ports.js';

const owner='019f0000-0000-7000-8000-000000000201' as never;const friend='019f0000-0000-7000-8000-000000000202' as never;const blocked='019f0000-0000-7000-8000-000000000203' as never;const now=new Date('2026-07-16T00:00:00Z');
const record=(id:string,visibility:'public'|'friends'|'private',expires:string|null):FootprintPolicyInput=>({id:id as never,authorId:owner,author:{name:'Owner'},displayPoint:{lat:1,lng:2},visibility,locationPrecision:'approximate',publishedAt:new Date('2026-07-15T00:00:00Z'),discoveryExpiresAt:expires?new Date(expires):null,message:id});
const records=[record('019f0000-0000-7000-8000-000000000211','public','2026-07-15T00:00:00Z'),record('019f0000-0000-7000-8000-000000000212','friends',null),record('019f0000-0000-7000-8000-000000000213','private',null)];
function query(){const source={async listByOwner(){return records;},async findById(id:never){return records.find((item)=>item.id===id)??null;}};const policy=new FootprintVisibilityPolicy({records:source,friendships:{async areAcceptedFriends(viewer){return viewer===friend;}},blocks:{async isEitherBlocked(viewer){return viewer===blocked;}},moderation:{async hasCaseAccess(){return false;}},now:()=>now});return new AuthorizedMemoryQuery(source,policy,{async listForFootprints(ids){return ids.map((id)=>({assetId:`asset-${id}`,footprintId:id,url:'https://example.test/photo.jpg',createdAt:now}));}},new InMemoryVisitorSource());}
describe('authorized memories',()=>{it('lets the owner see private history after discovery expiry',async()=>{await expect(query().map(owner,{userId:owner,sessionId:'s',roles:['user'],transport:'bearer'})).resolves.toHaveLength(3);});it('lets friends see non-private long-term history',async()=>{await expect(query().map(owner,{userId:friend,sessionId:'s',roles:['user'],transport:'bearer'})).resolves.toHaveLength(2);});it('denies blocked viewers and filters photo variants with the same policy',async()=>{const service=query();const viewer={userId:blocked,sessionId:'s',roles:['user'] as const,transport:'bearer' as const};await expect(service.map(owner,viewer)).resolves.toEqual([]);await expect(service.photos(owner,viewer)).resolves.toMatchObject({items:[]});});});
